# Configuration for weekly-digest - https://github.com/apps/weekly-digest
    publishDay: 0
    canPublishIssues: true
    canPublishPullRequests: true
    canPublishContributors: false
    canPublishStargazers: false
    canPublishCommits: true
  
