minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - '@ugrc/*'
storeDir: node_modules/.pnpm-store
onlyBuiltDependencies:
  - esbuild
  - sharp
allowBuilds:
  esbuild: true
  sharp: true
