name: New Issue (Create Blog Post)

on:
  # # Do not commit me to main, this is for testing purposes only
  push:
    branches:
      - bugfix/3430-bad-credentials-error
  issues:
    types: [opened]

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: 🎬 Update status
        id: update_status
        uses: actions/github-script@v8
        with:
          script: |
            const response = await github.rest.reactions.createForIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue?.number ?? 3430,
              content: 'eyes'
            });

            return response.data.id;
      - name: Generate Bot Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: 🔬 Check actor
        uses: tspascoal/get-user-teams-membership@v4
        id: checkUserMember
        with:
          username: ${{ github.actor }}
          team: ugrc-staff
          use_team_slug: true
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Debug membership
        run: echo "isTeamMember=${{ steps.checkUserMember.outputs.isTeamMember }}"

      - name: 🛑 Stop if not member
        if: ${{ steps.checkUserMember.outputs.isTeamMember == 'false' }}
        run: |
          echo "You cannot run this job."
          exit 86

      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v6
        with:
          show-progress: false

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v6

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: scripts/pnpm-lock.yaml

      - name: 📦 Install script dependencies
        working-directory: scripts
        run: pnpm install --frozen-lockfile

      - name: 📝 Create Blog Post
        working-directory: scripts
        run: node new-blog.mjs ${{ github.event.issue.number || 3430 }}

      - name: 📌 Create Pull Request
        uses: peter-evans/create-pull-request@v8
        id: cpr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'feat: create new blog post'
          title: 'feat: create new blog post'
          body: |
            This PR was automatically created by the "Issue opened (new blog)" workflow.

            closes #${{ github.event.issue.number || 3430 }}
          branch: feat/new-blog-post-${{ github.event.issue.number || 3430 }}
          draft: true

      - name: 🗑️ Remove reaction
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.reactions.deleteForIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue?.number ?? 3430,
              reaction_id: ${{ steps.update_status.outputs.result }}
            })

      - name: ✅ Set complete reaction
        uses: actions/github-script@v8
        if: ${{ steps.cpr.outputs.pull-request-number }}
        with:
          script: |
            github.rest.reactions.createForIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue?.number ?? 3430,
              content: 'rocket'
            });
