name: notfoundbot
on:
  schedule:
    - cron: "0 5 * * 1,5"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Fix links
        uses: tmcw/notfoundbot@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXCEPTIONS: ${{ secrets.NOT_FOUND_EXCEPTIONS}}
