name: Pull Request (TypeScript)

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test-types:
    name: TypeScript Check
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v6
        with:
          show-progress: false

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v6

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm

      - name: 📥 Download dependencies
        run: pnpm install --frozen-lockfile

      - name: 🧪 Check Types
        run: pnpm ts-check
